### ISSUE TITLE
chemacs-profile-paths used instead of chemacs-default-profile-paths

### ISSUE THREAD

**Issue by whxvd** [plexus/chemacs2#11] opened 2020-10-20 21:46 UTC
The line
```
(defvar chemacs-default-profile-path (or (car (seq-filter 'file-exists-p chemacs-profiles-paths)) (car chemacs-profiles-paths)))
```
uses `chemacs-profile-paths`. But it should use `chemacs-default-profile-paths`.

**Comment by ksafford** [comment] 2020-10-23 15:32
I believe this may be the cause of an issue I experience:
When starting emacs without a `--with-profile` flag I get 

    Wrong type argument: symbolp, ((spacemacs (user-emacs-directory . ~/spacemacs) (env (SPACEMACSDIR . ~/.spacemacs.d))))

despite having `spacemacs` in `.emacs-profile`

But things work as expected setting when specifying `--with-profile spacemacs`.

If this is the same issue, is there anything I can do to help out?

**Comment by whxvd** [comment] 2020-10-23 17:27
@ksafford: Yes, it is the cause of the error you experience. You can try PR #12 which fixes all currently reported issues.

**Comment by ksafford** [comment] 2020-10-23 18:32
Thanks, I can confirm this PR resolves the issue as well as several warnings and, as noted, doesn't run init files multiple times anymore. Nice work.

**Comment by plexus** [comment] 2020-10-26 14:22
#12 was merged so I'll close this. Please post a new issue if you still run into problems. Thanks!

**Closed by plexus** 2020-10-26 14:22 UTC
